# action.yml
name: 'F5 CLI Docker Action'
description: 'Run F5 CLI'
inputs:
  f5-cli-command:  # id of input
    description: 'F5 CLI command'
    required: true
outputs:
  f5-cli-command-output: # id of output
    description: 'F5 CLI command output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.f5-cli-command }}

