name: docker action

on:
  pull_request:
    paths-ignore:
    - ".github/**"

jobs:
  f5_cli_job:
    runs-on: ubuntu-latest
    name: A job run F5 CLI commands
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: F5 CLI login
        uses: ./ # Uses an action in the root directory
        id: login
        with:
          f5-cli-command: 'f5 login --authentication-provider bigip --host 7161a8da-3edd-4ba7-af94-84509ee08f4e.access.udf.f5.com --password ${{ secrets.bigip_password }} --user admin'
      # Use the output from the `hello` step
      - name: Get the F5 CLI command output
        run: echo "The F5 CLI command result is ${{ steps.login.outputs.f5-cli-command-output }}"
