#  This is a basic workflow to help you get started with Actions

name: CHANGED
env:
  URL:  "https://7161a8da-3edd-4ba7-af94-84509ee08f4e.access.udf.f5.com"


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths-ignore:
    - ".github/**"
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: get list of changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    
 #   - name: Read file contents
 #     id: read_file
 #     uses: andstor/file-reader-action@v1
 #     with:
 #       path: ${{ steps.files.outputs.all }}
 
 #  - name: File contents
  #    run: echo "${{ steps.read_file.outputs.contents }}"
      
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
          set -e
        curl -k -v \
          --url $URL/mgmt/shared/appsvcs/declare \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic YWRtaW46c3dhbmxhYnMx' \
          -d @${changed_file}
        done
