name: Deploy AS3

on:
  push:
    paths-ignore:
    - ".github/**"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install f5-cli
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: F5 CLI Login
      id: login
      run: |
        f5 config set-defaults --disable-ssl-warnings true --auto-approve
        f5 login --authentication-provider bigip --host 7161a8da-3edd-4ba7-af94-84509ee08f4e.access.udf.f5.com --user admin --password ${{ secrets.bigip_password }}
 
    - name: Check AS3 Installed
      id: verify
      run: | 
        echo ::set-output name=verify_results::$(f5 bigip extension as3 verify 2>&1 | jq '.installed')
        
    - name: show output
      run: |
        echo ${{ steps.verify.outputs.verify_results }}
        
    - name: get list of changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      
    - name: deploy as3 declaration
      id: deploy_as3
      if: ${{ steps.verify.outputs.verify_results }}
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "name of chnaged file = ${changed_file}"
          echo ::set-output name=deploy_results::$(f5 bigip extension as3 create --declaration ${changed_file} 2>&1 | jq '.results')
          echo "F5 AS3 declaration deploy result = ${{ steps.deploy_as3.outputs.deploy_results }}"
        done
    
 #   - name: show f5 as3 deploy result
 #     run: echo "F5 AS3 declaration deploy result = ${{ steps.deploy_as3.outputs.deploy_results }}"
